#define KEYSCAN_ESCAPE		1
#define KEYSCAN_1			2
#define KEYSCAN_2			3
#define KEYSCAN_3			4
#define KEYSCAN_4			5
#define KEYSCAN_5			6
#define KEYSCAN_6			7
#define KEYSCAN_7			8
#define KEYSCAN_8			9
#define KEYSCAN_9			10
#define KEYSCAN_0			11
#define KEYSCAN_HYPHEN		12
#define KEYSCAN_EQUALS		13
#define KEYSCAN_BACKSP		14
#define KEYSCAN_TAB			15
#define KEYSCAN_Q			16
#define KEYSCAN_W			17
#define KEYSCAN_E			18
#define KEYSCAN_R			19
#define KEYSCAN_T			20
#define KEYSCAN_Y			21
#define KEYSCAN_U			22
#define KEYSCAN_I			23
#define KEYSCAN_O			24
#define KEYSCAN_P			25
#define KEYSCAN_LEFTBR		26
#define KEYSCAN_RIGHTBR		27
#define KEYSCAN_ENTER		28
#define KEYSCAN_A			30
#define KEYSCAN_S			31
#define KEYSCAN_D			32
#define KEYSCAN_F			33
#define KEYSCAN_G			34
#define KEYSCAN_H			35
#define KEYSCAN_J			36
#define KEYSCAN_K			37
#define KEYSCAN_L			38
#define KEYSCAN_SEMICOLON	39
#define KEYSCAN_APOS		40
#define KEYSCAN_BACKTIC		41
#define KEYSCAN_BACKSLASH	43
#define KEYSCAN_Z			44
#define KEYSCAN_X			45
#define KEYSCAN_C			46
#define KEYSCAN_V			47
#define KEYSCAN_B			48
#define KEYSCAN_N			49
#define KEYSCAN_M			50
#define KEYSCAN_COMMA		51
#define KEYSCAN_PERIOD		52
#define KEYSCAN_SLASH		53
#define KEYSCAN_SPACE		57
#define KEYSCAN_CAPSLOCK	58
#define KEYSCAN_F1			59
#define KEYSCAN_F2			60
#define KEYSCAN_F3			61
#define KEYSCAN_F4			62
#define KEYSCAN_F5			63
#define KEYSCAN_F6			64
#define KEYSCAN_F7			65
#define KEYSCAN_F8			56
#define KEYSCAN_F9			67
#define KEYSCAN_F10			68
#define KEYSCAN_SHIFT		77
#define KEYSCAN_ALT			78
#define KEYSCAN_CTRL		79
#define KEYSCAN_F11			87
#define KEYSCAN_F12			88
#define KEYSCAN_HOME		199
#define KEYSCAN_UP			200
#define KEYSCAN_PGUP		201
#define KEYSCAN_LEFT		203
#define KEYSCAN_RIGHT		205
#define KEYSCAN_END			207
#define KEYSCAN_DOWN		208
#define KEYSCAN_PGDN		209
#define KEYSCAN_INSERT		210
#define KEYSCAN_DELETE		211

#define BUTTON_UP			1
#define BUTTON_RIGHT		2
#define BUTTON_DOWN			4
#define BUTTON_LEFT			8
#define BUTTON_A			16
#define BUTTON_B			32
#define BUTTON_X			64
#define BUTTON_Y			128
#define BUTTON_L			256
#define BUTTON_R			512
#define BUTTON_START		1024
#define BUTTON_SELECT		2048
