//Prototypes for library functions
extern void SetBold(bool);
extern int Write(const char*, ...);
//extern void WriteString(const char*);
//extern void WriteInt(int);
extern void WriteChar(char);
//extern void WriteHex(int);
//extern void WriteHex8(int8_t);
//extern void WriteHex16(int16);
//extern void WriteHex32(int);
extern void SetCursor(int, int);
extern void SetTextColor(int, int);
extern int Format(char*, const char*, ...);
extern void ClearScreen(void);
extern void ResetPalette(void);
extern void DisplayPicture(TImageFile*);
extern void FadeToBlack();
extern void FadeFromBlack();
extern void FadeToWhite();
extern void FadeFromWhite();
extern void DrawString(const char*, int, int, int);
extern void DrawFormat(const char*, int, int, int, ...);
extern void DrawChar(char, int, int, int);
extern void DrawLine(int, int, int, int, int, uint8_t*);
extern void FloodFill(int, int, int, uint8_t*);
extern void SetTextMode80x30(void);
extern void SetTextMode80x60(void);
extern void SetTextMode(int);
extern void SetBitmapMode16(int);
extern void SetBitmapMode256(int);
extern void EnableObjects(bool);
extern void WaitForVBlank(void);
extern void WaitForVBlanks(int);
extern void DmaCopy(void*, const void*, size_t, int);
extern void DmaClear(void*, int, size_t, int);
extern void MidiReset(void);
extern void RleUnpack(int8_t*, int8_t*, size_t);
extern int OpenFile(TFileHandle*, const char*, char);
extern int CloseFile(TFileHandle*);
extern int ReadFile(TFileHandle*, void*, size_t);
extern int WriteFile(TFileHandle*, void*, size_t);
extern int SeekFile(TFileHandle*, uint32_t, int);
extern int TruncateFile(TFileHandle*);
extern int FlushFile(TFileHandle*);
extern char* FileReadLine(TFileHandle*, char*, size_t);
extern int FilePutChar(TFileHandle*, char);
extern int FileWriteLine(TFileHandle*, const char*);
extern unsigned int FilePosition(TFileHandle*);
extern bool FileEnd(TFileHandle*);
extern size_t FileSize(TFileHandle*);
extern int OpenDir(TDirHandle*, const char*);
extern int CloseDir(TDirHandle*);
extern int ReadDir(TDirHandle*, TFileInfo*);
extern int FindFirst(TDirHandle*, TFileInfo*, const char*, const char*);
extern int FindNext(TDirHandle*, TFileInfo*);
extern int FileStat(const char*, TFileInfo*);
extern int UnlinkFile(const char*);
extern int RenameFile(const char*, const char*);
extern int FileTouch(const char*, TFileInfo*);
extern int FileAttrib(const char* path, char attrib);
extern int MakeDir(const char*);
extern int ChangeDir(const char*);
extern int GetCurrentDir(char*, size_t);
extern int GetLabel(char, char*, unsigned long*);
extern int GetFree(char);
extern const char* FileErrStr(int);
extern uint8_t GetNumDrives();



extern void DrawChar4_320(char, int, int, int);
extern void DrawChar4_640(char, int, int, int);
extern void DrawChar8_320(char, int, int, int);
extern void DrawChar8_640(char, int, int, int);
