//Prototypes for library functions
extern void SetBold(int32_t);
extern int Write(const char*, ...);
//extern void WriteString(const char*);
//extern void WriteInt(int32_t);
extern void WriteChar(char);
//extern void WriteHex(int32_t);
//extern void WriteHex8(int8_t);
//extern void WriteHex16(int16);
//extern void WriteHex32(int32_t);
extern void SetCursor(int32_t, int32_t);
extern void SetTextColor(int32_t, int32_t);
extern int Format(char*, const char*, ...);
extern void ClearScreen(void);
extern void ResetPalette(void);
extern void DisplayPicture(TImageFile*);
extern void FadeToBlack();
extern void FadeFromBlack();
extern void FadeToWhite();
extern void FadeFromWhite();
extern void DrawString(const char*, int32_t, int32_t, int32_t);
extern void DrawFormat(const char*, int32_t, int32_t, int32_t, ...);
extern void DrawChar(char, int32_t, int32_t, int32_t);
extern void SetTextMode80x30(void);
extern void SetTextMode80x60(void);
extern void SetTextMode(int32_t);
extern void SetBitmapMode16(int32_t);
extern void SetBitmapMode256(int32_t);
extern void EnableObjects(int32_t);
extern void WaitForVBlank(void);
extern void WaitForVBlanks(int32_t);
extern void DmaCopy(void*, const void*, uint32_t, int32_t);
extern void DmaClear(void*, int32_t, uint32_t, int32_t);
extern void MidiReset(void);
extern void RleUnpack(int8_t*, int8_t*, uint32_t);
extern int32_t OpenFile(TFileHandle*, const char*, char);
extern int32_t CloseFile(TFileHandle*);
extern int32_t ReadFile(TFileHandle*, void*, uint32_t);
extern int32_t WriteFile(TFileHandle*, void*, uint32_t);
extern int32_t SeekFile(TFileHandle*, uint32_t, int32_t);
extern int32_t TruncateFile(TFileHandle*);
extern int32_t FlushFile(TFileHandle*);
extern char* FileReadLine(TFileHandle*, char*, uint32_t);
extern int32_t FilePutChar(TFileHandle*, char);
extern int32_t FileWriteLine(TFileHandle*, const char*);
extern uint32_t FilePosition(TFileHandle*);
extern int32_t FileEnd(TFileHandle*);
extern uint32_t FileSize(TFileHandle*);
extern int32_t OpenDir(TDirHandle*, const char*);
extern int32_t CloseDir(TDirHandle*);
extern int32_t ReadDir(TDirHandle*, TFileInfo*);
extern int32_t FindFirst(TDirHandle*, TFileInfo*, const char*, const char*);
extern int32_t FindNext(TDirHandle*, TFileInfo*);
extern int32_t FileStat(const char*, TFileInfo*);
extern int32_t UnlinkFile(const char*);
extern int32_t RenameFile(const char*, const char*);
extern int32_t FileTouch(const char*, TFileInfo*);
extern int32_t MakeDir(const char*);
extern int32_t ChangeDir(const char*);
extern int32_t GetCurrentDir(char*, int32_t);
extern int32_t GetLabel(char*);
extern const char* FileErrStr(int32_t);
extern int32_t GetNumDrives();



extern void DrawChar4_320(char, int32_t, int32_t, int32_t);
extern void DrawChar4_640(char, int32_t, int32_t, int32_t);
extern void DrawChar8_320(char, int32_t, int32_t, int32_t);
extern void DrawChar8_640(char, int32_t, int32_t, int32_t);
